### ISSUE TITLE
feature: support database/sql

### ISSUE THREAD

**Issue by johejo** [sonatard/noctx#8]
Thank you for the wonderful linter.

This linter seems to be mainly net/http, but is it out of scope to issue a warning to methods that use database/sql without context.Context?

**Comment by ldez** [comment]
@sonatard @michaelpeterswa I propose discussing the topic here.

**Comment by michaelpeterswa** [comment]
Good morning, it seems to me like it would be beneficial to have some ability to control what packages this is enforced for, while I think it's a good idea to have it apply everywhere, the flexibility of enabling it on a per package basis seems useful, especially when people/teams are unable to change all the usages at once.

**Comment by ldez** [comment]
You can control the exclusion inside golangci-lint.

https://golangci-lint.run/usage/false-positives/#exclude

```yml
linters:
  enable:
    - noctx
  exclusions:
    rules:
      - path: pkg/foo/
        linters:
          - noctx
```

Having this granularity inside a linter doesn't seem right.

**Comment by michaelpeterswa** [comment]
I agree with that, where I disagree is enforcing both `net/http` and `database/sql` at the same time, you should be able to select one or the other. Which is one of the reasons I had a separate linter in the first place. If you want both, that's totally fine also.

**Comment by ldez** [comment]
```yml
linters:
  enable:
    - noctx
  exclusions:
    rules:
      - path: pkg/foo/
        text: 'use \(\*database/sql\.(DB|Tx)\)\.'
        linters:
          - noctx
```

**Comment by michaelpeterswa** [comment]
Interesting, that could work, thank you. We run the same set of GH Actions across all 100+ of our active repositories, so a per-path basis is untenable, but that's just our use-case.

**Comment by ldez** [comment]
```yml
linters:
  enable:
    - noctx
  exclusions:
    rules:
      - text: 'use \(\*database/sql\.(DB|Tx)\)\.'
        linters:
          - noctx
```
